services:
  - type: web
    name: waitnot-restaurant
    runtime: node
    buildCommand: npm run render-build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
