platform :ios, '15.0'
use_frameworks! :linkage => :static

project 'App.xcodeproj'

install! 'cocoapods', :disable_input_output_paths => true

target 'App' do
  pod 'Firebase/Messaging'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
